import {Component,inject,HostListener} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute,Router,RouterLink,RouterLinkActive,CanDeactivateFn} from '@angular/router';
import {CatalogService} from '../services/catalog.service';
import {AuthService} from '../services/auth.service';
import {normalize} from '../services/contact';
import {priceLabel,PLATFORMS,validateItem,validateType} from '../services/local-store';
import type {Product,AffiliateProduct,CatalogType,ItemStatus} from '../data/models';
import {ImagePickerComponent} from './image-picker';
@Component({selector:'crica-admin',standalone:true,imports:[FormsModule,RouterLink,RouterLinkActive,ImagePickerComponent],template:`
<div class="admin-layout"><aside class="admin-sidebar"><a routerLink="/admin/loja" class="admin-brand"><img src="/assets/crica-studio-logo.png" alt="Crica Studio" width="140" height="76"></a><span class="sidebar-label">ADMINISTRAÇÃO</span><nav aria-label="Administração"><a routerLink="/admin/loja" routerLinkActive="active" ariaCurrentWhenActive="page"><span aria-hidden="true">▦</span> Produtos da loja</a><a routerLink="/admin/fornecedores" routerLinkActive="active" ariaCurrentWhenActive="page"><span aria-hidden="true">↗</span> Fornecedores</a><a routerLink="/admin/tipos" routerLinkActive="active" ariaCurrentWhenActive="page"><span aria-hidden="true">≡</span> Tipos</a><a routerLink="/admin/configuracoes" routerLinkActive="active" ariaCurrentWhenActive="page"><span aria-hidden="true">⚙</span> Configurações</a></nav><div class="sidebar-bottom"><a routerLink="/loja">← Ver site</a><button type="button" (click)="logout()">Sair da demonstração</button><small>Crica Studio<br>Ideias que ganham forma.</small></div></aside>
<div class="admin-workspace"><header class="admin-topbar"><span>Seu studio, organizado.</span><span class="demo-badge">Demonstração local</span></header><main class="admin-main"><div class="admin-page-heading"><div><span class="eyebrow">{{editing?'CADASTRO':section==='configuracoes'?'PREFERÊNCIAS':'SEU CATÁLOGO'}}</span><h1>{{editing?(isNew?'Novo cadastro':'Editar cadastro'):title}}</h1><p>{{subtitle}}</p></div>@if(!editing&&section!=='configuracoes'){<button class="primary" (click)="create()">+ {{section==='tipos'?'Novo tipo':section==='loja'?'Novo produto':'Nova indicação'}}</button>}</div>
@if(catalog.storageWarning()){<div class="admin-notice" role="status">{{catalog.storageWarning()}}</div>}
@if(notice){<div class="success-notice" role="status">{{notice}}</div>}
@if(errors.length){<div class="error-summary" role="alert" tabindex="-1" id="form-errors"><strong>Confira antes de salvar</strong><ul>@for(error of errors;track error){<li>{{error}}</li>}</ul></div>}
@if(section==='configuracoes'){
<section class="admin-panel settings-panel"><h2>Atendimento pelo WhatsApp</h2><p>Um único contato para todos os pedidos da loja.</p><form (ngSubmit)="saveSettings()"><label for="whatsapp">Número internacional</label><input id="whatsapp" name="whatsapp" type="tel" inputmode="numeric" [(ngModel)]="whatsapp" placeholder="Código do país + DDD + número"><small>Somente dígitos. Deixe vazio para manter a prévia da mensagem com “Contato em configuração”.</small><button class="primary" type="submit">Salvar configurações</button></form></section><section class="admin-panel settings-panel"><h2>Dados desta demonstração</h2><p>As alterações ficam neste navegador, inclusive após atualizar a página. Outro dispositivo começa com os exemplos iniciais. O login é apenas uma simulação.</p><p>O catálogo público deste navegador acompanha os cadastros publicados. Fotos e rascunhos também ficam armazenados localmente.</p><button class="secondary danger-button" type="button" (click)="reset()">Restaurar dados de demonstração</button><small>Apaga seus cadastros locais e restaura os exemplos. Pediremos confirmação.</small></section>
}@else if(editing&&section==='tipos'){
<section class="admin-panel type-editor"><form (ngSubmit)="saveType()"><label for="type-name">Nome do tipo *</label><input id="type-name" name="type-name" [(ngModel)]="typeDraft.name" maxlength="60" required placeholder="Ex.: Caneca"><label for="scope">Onde usar *</label><select id="scope" name="scope" [(ngModel)]="typeDraft.scope"><option value="shop">Loja</option><option value="suppliers">Fornecedores</option><option value="both">Ambos</option></select><label class="check-label"><input type="checkbox" name="active" [(ngModel)]="typeDraft.active"> Ativo para novos cadastros</label><p class="field-help">Desativar um tipo não esconde produtos existentes. Tipos já utilizados são preservados para manter os vínculos.</p><div class="form-actions"><button class="primary" type="submit">Salvar tipo</button><button class="secondary" type="button" (click)="cancel()">Cancelar</button></div></form></section>
}@else if(editing){
<form class="item-editor" (ngSubmit)="save()"><div class="editor-main"><section class="admin-panel"><h2>Informações do produto</h2><label for="item-title">Título *</label><input id="item-title" name="title" [(ngModel)]="draft.name" required maxlength="120" placeholder="Como o produto aparecerá no catálogo"><div class="form-two"><div><label for="item-type">Tipo *</label><select id="item-type" name="type" [(ngModel)]="draft.typeId" required><option value="">Selecione</option>@for(t of availableTypes;track t.id){<option [value]="t.id">{{t.name}}{{t.active?'':' (inativo)'}}</option>}</select></div><div><label for="item-order">Ordem de exibição</label><input id="item-order" name="order" type="number" min="0" step="1" [(ngModel)]="draft.order" required></div></div><label for="short-description">Descrição curta</label><textarea id="short-description" name="description" [(ngModel)]="draft.description" rows="3" maxlength="240" placeholder="Resuma o produto para o card"></textarea><small>{{draft.description.length}}/240 caracteres · Necessária para publicar.</small>
@if(section==='loja'){<label for="full-description">Descrição completa</label><textarea id="full-description" name="fullDescription" [(ngModel)]="draft.fullDescription" rows="5" placeholder="Detalhes que ajudam o cliente a escolher"></textarea>}
</section><section class="admin-panel"><h2>{{section==='loja'?'Fotos do produto':'Foto principal'}}</h2><p>A primeira imagem aparece no card.</p><crica-image-picker [images]="images" [limit]="section==='loja'?5:1" (changed)="images=$event"/></section>
@if(section==='loja'){<section class="admin-panel"><h2>Personalização e características</h2><label for="characteristics">Características</label><textarea id="characteristics" name="characteristics" [(ngModel)]="characteristics" rows="3" placeholder="Uma característica por linha"></textarea><label for="personalization">Opções de personalização</label><textarea id="personalization" name="personalization" [(ngModel)]="personalization" rows="3" placeholder="Nome&#10;Frase&#10;Logotipo"></textarea><small>Uma opção por linha. Inclua apenas informações que você pode confirmar.</small></section>}
</div><aside class="editor-aside">
@if(section==='loja'){<section class="admin-panel"><h2>Preço</h2><label for="price-mode">Como apresentar</label><select id="price-mode" name="priceMode" [(ngModel)]="draft.priceMode"><option value="consult">Sob consulta</option><option value="fixed">Preço fixo</option><option value="from">A partir de</option></select>@if(draft.priceMode!=='consult'){<label for="price">Valor em R$ *</label><input id="price" name="price" type="number" min="0.01" step="0.01" [(ngModel)]="draft.price" required>}<p class="field-help">O pedido continua pelo WhatsApp, sem carrinho ou pagamento no site.</p></section>}
@else{<section class="admin-panel"><h2>Destino da indicação</h2><label for="platform">Plataforma *</label><select id="platform" name="platform" [(ngModel)]="draft.platform">@for(p of platforms;track p){<option [value]="p">{{p}}</option>}</select><label for="seller">Loja ou vendedor</label><input id="seller" name="seller" [(ngModel)]="draft.seller" maxlength="120" placeholder="Opcional"><label for="affiliate-url">Link de afiliado</label><input id="affiliate-url" name="url" type="url" [(ngModel)]="draft.url" placeholder="https://…"><small>Cole o link completo. Os parâmetros serão preservados.</small><label class="check-label"><input type="checkbox" name="demoListing" [(ngModel)]="draft.demoListing"> Indicação de demonstração</label><p class="field-help">Permite experimentar sem foto ou anúncio real. O botão mostra uma explicação até você configurar o destino.</p></section>}
<section class="admin-panel"><h2>Publicação</h2><label for="status">Status</label><select id="status" name="status" [(ngModel)]="draft.status"><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="inactive">Inativo</option></select><p class="field-help">Somente os publicados aparecem no site deste navegador.</p><button class="primary full" type="submit">Salvar alterações</button><button class="secondary full" type="button" (click)="save('draft')">Salvar rascunho</button><button class="secondary full" type="button" (click)="save('published')">Publicar</button><button class="text-link full" type="button" (click)="cancel()">Cancelar</button></section></aside></form>
}@else if(section==='tipos'){
<div class="admin-panel"><div class="admin-filters"><label class="admin-search"><span class="sr-only">Buscar tipos</span><input type="search" placeholder="Buscar tipos" [(ngModel)]="query"></label><select aria-label="Filtrar tipos por situação" [(ngModel)]="status"><option value="all">Todos os tipos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select></div><div class="type-list">@for(t of filteredTypes;track t.id){<article class="type-row"><div><h3>{{t.name}}</h3><p>{{scopeLabel(t.scope)}} · {{usage(t.id)}} {{usage(t.id)===1?'item vinculado':'itens vinculados'}}</p></div><span class="status-pill" [class.published]="t.active">{{t.active?'Ativo':'Inativo'}}</span><div class="row-actions"><button (click)="editType(t)">Editar</button><button (click)="toggleType(t)">{{t.active?'Desativar':'Ativar'}}</button></div></article>}@empty{<div class="empty"><h3>Nenhum tipo encontrado</h3><button class="secondary" (click)="clear()">Limpar filtros</button></div>}</div></div>
}@else{
<div class="admin-stats"><div><span>Publicados</span><strong>{{count('published')}}</strong><small>Visíveis no catálogo</small></div><div><span>Rascunhos</span><strong>{{count('draft')}}</strong><small>Ideias em preparação</small></div><div><span>Inativos</span><strong>{{count('inactive')}}</strong><small>Fora do catálogo</small></div></div>
<section class="admin-panel catalog-list-panel"><div class="admin-filters"><label class="admin-search"><span class="sr-only">Buscar cadastros</span><input type="search" placeholder="Buscar por título" [(ngModel)]="query"></label><select aria-label="Filtrar por tipo" [(ngModel)]="typeFilter"><option value="all">Todos os tipos</option>@for(t of sectionTypes;track t.id){<option [value]="t.id">{{t.name}}</option>}</select><select aria-label="Filtrar por status" [(ngModel)]="status"><option value="all">Todos os status</option><option value="published">Publicados</option><option value="draft">Rascunhos</option><option value="inactive">Inativos</option></select>@if(section==='fornecedores'){<select aria-label="Filtrar por plataforma" [(ngModel)]="platformFilter"><option value="all">Todas as plataformas</option>@for(p of platforms;track p){<option [value]="p">{{p}}</option>}</select>}</div><div class="admin-results"><span aria-live="polite">{{filtered.length}} {{filtered.length===1?'cadastro':'cadastros'}}</span>@if(query||status!=='all'||typeFilter!=='all'||platformFilter!=='all'){<button class="text-link" (click)="clear()">Limpar filtros</button>}</div>
<div class="admin-table-header"><span>Produto</span><span>{{section==='loja'?'Preço':'Plataforma'}}</span><span>Status</span><span>Ações</span></div>
@for(item of filtered;track item.id){<article class="admin-product-row"><div class="row-product">@if(itemImage(item)){<img [src]="itemImage(item)" alt="" (error)="$any($event.target).style.visibility='hidden'">}@else{<div class="row-image-placeholder" aria-hidden="true">C</div>}<div><button class="row-title" (click)="edit(item)">{{item.name}}</button><p>{{catalog.typeName(item.typeId)}} · Ordem {{item.order}}</p></div></div><div class="row-meta">{{section==='loja'?price(item):$any(item).platform}}</div><span class="status-pill" [class.published]="item.status==='published'" [class.draft]="item.status==='draft'">{{statusLabel(item.status)}}</span><div class="row-actions"><button (click)="edit(item)" [attr.aria-label]="'Editar '+item.name">Editar</button><button (click)="duplicate(item)" [attr.aria-label]="'Duplicar '+item.name">Duplicar</button><button (click)="toggle(item)" [attr.aria-label]="(item.status==='inactive'?'Ativar ':'Desativar ')+item.name">{{item.status==='inactive'?'Ativar':'Desativar'}}</button></div></article>}@empty{<div class="empty"><h3>Nenhum cadastro encontrado</h3><p>Tente outro título ou limpe os filtros.</p><button class="secondary" (click)="clear()">Limpar filtros</button></div>}
</section><p class="admin-footnote">Publicado aqui, visível no catálogo deste navegador. Rascunhos ficam só na administração.</p>
}
</main></div></div>`})
export class AdminComponent {
 catalog=inject(CatalogService);auth=inject(AuthService);router=inject(Router);route=inject(ActivatedRoute);
 section=this.route.snapshot.data['section'] as string;platforms=PLATFORMS;query='';status='all';typeFilter='all';platformFilter='all';notice='';errors:string[]=[];editing=false;isNew=false;baseline='';whatsapp=this.catalog.whatsappNumber;
 draft:Product&Partial<AffiliateProduct>={id:'',name:'',category:'',description:'',images:[],characteristics:[],personalization:[],demo:true};images:string[]=[];characteristics='';personalization='';typeDraft:CatalogType={id:'',name:'',scope:'both',active:true};
 get title(){return ({loja:'Produtos da loja',fornecedores:'Fornecedores',tipos:'Tipos de produto',configuracoes:'Configurações'} as Record<string,string>)[this.section];}
 get subtitle(){return this.editing?'Dê forma aos detalhes que aparecem no catálogo.':({loja:'Cuide dos modelos que levam a ideia do cliente até a Crica.',fornecedores:'Cada indicação tem seu próprio cadastro e sua plataforma.',tipos:'Organize seus produtos com tipos simples e reutilizáveis.',configuracoes:'Contato e preferências da sua demonstração.'} as Record<string,string>)[this.section];}
 get items(){return this.section==='loja'?this.catalog.allProducts:this.catalog.allAffiliates;}
 get filtered(){return this.items.filter(p=>normalize(p.name).includes(normalize(this.query))&&(this.status==='all'||p.status===this.status)&&(this.typeFilter==='all'||p.typeId===this.typeFilter)&&(this.platformFilter==='all'||(p as AffiliateProduct).platform===this.platformFilter));}
 get sectionTypes(){return this.catalog.types.filter(t=>t.scope==='both'||t.scope===(this.section==='loja'?'shop':'suppliers'));}
 get availableTypes(){return this.sectionTypes.filter(t=>t.active||t.id===this.draft.typeId);}
 get filteredTypes(){return this.catalog.types.filter(t=>normalize(t.name).includes(normalize(this.query))&&(this.status==='all'||t.active===(this.status==='active')));}
 count(status:ItemStatus){return this.items.filter(p=>p.status===status).length;}
 price(item:Product|AffiliateProduct){return priceLabel(item as Product);}
 statusLabel(status?:ItemStatus){return status==='published'?'Publicado':status==='inactive'?'Inativo':'Rascunho';}
 scopeLabel(scope:string){return scope==='shop'?'Loja':scope==='suppliers'?'Fornecedores':'Loja e Fornecedores';}
 usage(id:string){return [...this.catalog.allProducts,...this.catalog.allAffiliates].filter(p=>p.typeId===id).length;}
 itemImage(item:Product|AffiliateProduct){return 'images' in item?item.images[0]:(item as AffiliateProduct).image;}
 snapshot(){return JSON.stringify(this.section==='tipos'?this.typeDraft:{draft:this.draft,images:this.images,characteristics:this.characteristics,personalization:this.personalization});}
 get dirty(){return this.editing&&this.baseline!==this.snapshot()||this.section==='configuracoes'&&this.whatsapp!==this.catalog.whatsappNumber;}
 canLeave(){return !this.dirty||window.confirm('Há alterações não salvas. Deseja sair sem salvar?');}
 @HostListener('window:beforeunload',['$event'])beforeUnload(event:BeforeUnloadEvent){if(this.dirty){event.preventDefault();event.returnValue='';}}
 create(){this.errors=[];this.notice='';this.isNew=true;this.editing=true;if(this.section==='tipos'){this.typeDraft={id:'item-'+Date.now().toString(36)+'-'+Array.from(crypto.getRandomValues(new Uint32Array(2)),n=>n.toString(36)).join('-'),name:'',scope:'both',active:true};}else{this.draft={id:'item-'+Date.now().toString(36)+'-'+Array.from(crypto.getRandomValues(new Uint32Array(2)),n=>n.toString(36)).join('-'),name:'',category:'',typeId:'',description:'',fullDescription:'',images:[],characteristics:[],personalization:[],demo:true,priceMode:'consult',status:'draft',order:(this.items.reduce((n,p)=>Math.max(n,p.order||0),0))+10,platform:'Shopee',seller:'',url:'',demoListing:false};this.images=[];this.characteristics='';this.personalization='';}this.baseline=this.snapshot();window.scrollTo(0,0);}
 edit(item:Product|AffiliateProduct){this.errors=[];this.notice='';this.isNew=false;this.editing=true;this.draft={images:[],characteristics:[],personalization:[],demo:true,...structuredClone(item)};this.images='images' in item?[...item.images]:item.image?[item.image]:[];this.characteristics=this.draft.characteristics.join('\n');this.personalization=this.draft.personalization.join('\n');this.baseline=this.snapshot();window.scrollTo(0,0);}
 duplicate(item:Product|AffiliateProduct){this.edit(item);this.draft.id='item-'+Date.now().toString(36)+'-'+Array.from(crypto.getRandomValues(new Uint32Array(2)),n=>n.toString(36)).join('-');this.draft.name=item.name+' (cópia)';this.draft.status='draft';this.isNew=true;this.baseline=this.snapshot();this.notice='Cópia preparada como rascunho. Ajuste os dados e salve para cadastrá-la.';}
 cancel(){if(!this.canLeave())return;this.editing=false;this.errors=[];this.notice='';}
 error(error:unknown){this.errors=[error instanceof Error?error.message:'Não foi possível salvar.'];setTimeout(()=>document.getElementById('form-errors')?.focus());}
 save(status?:ItemStatus){this.errors=[];const d={...structuredClone(this.draft),status:status??this.draft.status};const item=this.section==='loja'?{...d,images:[...this.images],characteristics:this.characteristics.split('\n').map(s=>s.trim()).filter(Boolean),personalization:this.personalization.split('\n').map(s=>s.trim()).filter(Boolean)}:{...d,image:this.images[0]||undefined};try{if(this.section==='loja')this.catalog.saveProduct(item as Product);else this.catalog.saveAffiliate(item as AffiliateProduct);this.editing=false;this.notice=d.status==='published'?'Cadastro publicado. Ele já aparece no catálogo deste navegador.':d.status==='inactive'?'Cadastro salvo como inativo.':'Rascunho salvo. Ele ainda não aparece no catálogo.';window.scrollTo(0,0);}catch(e){this.error(e);}}
 toggle(item:Product|AffiliateProduct){this.errors=[];try{const updated={...item,status:(item.status==='inactive'?'draft':'inactive') as ItemStatus};this.section==='loja'?this.catalog.saveProduct(updated as Product):this.catalog.saveAffiliate(updated as AffiliateProduct);this.notice=updated.status==='draft'?'Cadastro reativado como rascunho. Revise e publique quando estiver pronto.':'Cadastro desativado e retirado do catálogo.';}catch(e){this.error(e);}}
 editType(t:CatalogType){this.editing=true;this.isNew=false;this.typeDraft=structuredClone(t);this.errors=[];this.notice='';this.baseline=this.snapshot();}
 saveType(){try{this.catalog.saveType(this.typeDraft);this.editing=false;this.errors=[];this.notice='Tipo salvo. Os cadastros vinculados acompanham o nome atualizado.';}catch(e){this.error(e);}}
 toggleType(t:CatalogType){try{this.catalog.saveType({...t,active:!t.active});this.errors=[];this.notice=t.active?'Tipo desativado para novos cadastros. Os itens existentes foram preservados.':'Tipo ativado.';}catch(e){this.error(e);}}
 saveSettings(){try{this.catalog.saveSettings(this.whatsapp.trim());this.whatsapp=this.catalog.whatsappNumber;this.errors=[];this.notice='Configurações salvas neste navegador.';}catch(e){this.error(e);}}
 reset(){if(!window.confirm('Restaurar os exemplos? Todos os cadastros, fotos e configurações salvos neste navegador serão substituídos.'))return;try{this.catalog.reset();this.whatsapp=this.catalog.whatsappNumber;this.errors=[];this.notice='Dados de demonstração restaurados.';}catch(e){this.error(e);}}
 clear(){this.query='';this.status='all';this.typeFilter='all';this.platformFilter='all';}
 logout(){if(!this.canLeave())return;this.editing=false;this.whatsapp=this.catalog.whatsappNumber;this.auth.logout();this.router.navigateByUrl('/login');}
}
export const unsavedGuard:CanDeactivateFn<AdminComponent>=component=>component.canLeave();
